### ISSUE TITLE
[Feature Request] styleComment should colorize the "//" comment tag as well

### ISSUE THREAD

**Issue by kafnod** [StarlaneStudios/vscode-comment-anchors#31]

**Comment by ctf0** [comment]
this could be done by changing the tag, but maybe instead of having the tag as a fixed string it could be a regex which will add much more flexibility, @macjuul what u think ?

**Comment by kpatelPro** [comment]
styleComment could have options instead of boolean choices:
 - tagOnly (currently styleComment:false)
 - tagAndFollowing (currently styleComment:true)
 - tagAndBefore (from first non-whitespace character to last character of tag)
    * accomplishes what the issue requests, assuming the comment is at start of line
 - lineTrimmed (from first non-whitespace character to last non-whitespace character)
 - lineFull (from column 0 to last non-whitespace character, or to config'd column number)
